import './globals.css'
import { Inter } from 'next/font/google'
import NavbarComponent from './navbar'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'TechIt',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <NavbarComponent/>
        {children}
        </body>
    </html>
  )
}
